Please use the form below to create a product

<?php 
$this->form->setAction($this->url());
?>
<?php echo $this->form ?>
    <?php
    /*
    $form = new Zend_Form();
$form->setEnctype('multipart/form-data');
$form->setAction('index2.php');

// Button
$button = new Zend_Form_Element_Submit('submit');
$form->addElement($button);

// File Upload Elements
$element = new Zend_Form_Element_File('firstfile');
$element2 = new Zend_Form_Element_File('secondfile');

// 3-Level subform
$subform0 = new Zend_Form_SubForm();
$subform0->addElement($element);
$subform0->addElement($element2);
$subform1 = new Zend_Form_SubForm();
$subform1->addSubform($subform0, 'subform0');
$subform2 = new Zend_Form_SubForm();
$subform2->addSubform($subform1, 'subform1');
$subform3 = new Zend_Form_SubForm();
$subform3->addSubform($subform2, 'subform2');
$form->addSubform($subform3, 'subform3');

$form->setView(new Zend_View());
echo $form;
*/
    ?>
