<?= $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Zend Tickets</title>
  <base href="<?php echo $this->baseUrl(); ?>" />
  <?= $this->dojo() ?>
  <?= $this->headLink()->appendStylesheet('/css/install.css') ?>
  <?= $this->headScript() ?>
</head>
<body class="tundra">
<h1>Zend Tickets Installer</h1>
<div id="uiContainer">
    <?php echo $this->layout()->content ?>
</div>
<?php echo $this->inlineScript() ?>
</body>
</html>
