<?php
$this->dojo()->enable();
$this->dojo()->requireModule('dijit.layout.BorderContainer');
$this->dojo()->requireModule('dijit.layout.ContentPane');
$this->dojo()->requireModule('dijit.layout.AccordionContainer');
$this->dojo()->requireModule('dijit.form.Button');
?>
<?php $this->borderContainer()->captureStart('masterLayout', array('design' => 'headline','persist' => true), array('style' => 'width: 100%; height: 500px;')) ?>

<!-- Left Sidebar -->
<?php $this->contentPane()->captureStart('leftSidebar', array('region' => 'leading', 'style' => 'width: 15%', 'splitter' => true)) ?>
<p>
    <?php foreach($this->navigation as $page) { ?>
        <?php echo $page ?>
    <?php } ?>
</p>
<?php echo $this->contentPane()->captureEnd('leftSidebar') ?>

<!-- Main -->
<?php $this->contentPane()->captureStart('main', array('region' => 'center')) ?>