<?php
$this->dojo()->enable();
$this->dojo()->requireModule('dijit.layout.BorderContainer');
$this->dojo()->requireModule('dijit.layout.ContentPane');
$this->dojo()->requireModule('dijit.layout.AccordionContainer');
$this->dojo()->requireModule('dijit.form.Button');
?>
<div id="disclaimer" style="display: none">
    <h2>Step 1: Installation requirements</h2>
    <p>
        This is a highly experimental php application, so use at your own
        digression.
    </p>
    <p>
        Supported Databases:<br />
        <?php
        $this->form->setAction($this->url());
        echo $this->form;
        ?>
    </p>
</div>
<div id="leftSideNav" style="display: none">
    <p>
        <a href="">Step 1</a>
        <a href="">Step 2</a>
    </p>
</div>
<script type="text/javascript">
    dojo.addOnLoad(function() {
        var outerBc = new dijit.layout.BorderContainer({
            "design": "sidebar",
            "style": "height: 80%; min-height: 400px;"
        },
        "uiContainer");

        var leftSidebar = new dijit.layout.ContentPane({
            "title": "Sidebar",
            "region": "leading",
            "style": "width: 15%;",
            "splitter": "true",
            "id": "leftSidebar",
            "content": dojo.byId("leftSideNav").innerHTML
        });
        outerBc.addChild(leftSidebar);

        var rightContent = new dijit.layout.ContentPane({
            "id": "uiContent",
            "region": "center",
            "content": dojo.byId("disclaimer").innerHTML
        });

        outerBc.addChild(rightContent);
        outerBc.startup();

    });
</script>